import type { PrinterProfile } from './printer-profile.types.js';

const now = '2026-01-01T00:00:00.000Z';

/**
 * Reusable profiles for common thermal receipt printer families (Step 8) — seeded in code, not
 * the database, so upgrading the agent can safely ship new/updated built-ins without a migration.
 * `PrinterProfileService` merges these with user-created custom profiles at read time.
 */
export const BUILT_IN_PRINTER_PROFILES: PrinterProfile[] = [
  {
    id: 'builtin-generic-escpos-80mm',
    name: 'Generic ESC/POS 80mm',
    model: null,
    paperWidth: '80mm',
    defaultRenderer: 'escpos',
    supportedDrivers: ['escpos-usb', 'network', 'raw'],
    encoding: 'cp437',
    capabilities: ['usb', 'network', 'raw-bytes', 'escpos', 'images', 'cash-drawer', 'cut-paper'],
    imageSupport: true,
    qrSupport: true,
    barcodeSupport: true,
    cashDrawerSupport: true,
    cutSupport: true,
    isBuiltin: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'builtin-generic-escpos-58mm',
    name: 'Generic ESC/POS 58mm',
    model: null,
    paperWidth: '58mm',
    defaultRenderer: 'escpos',
    supportedDrivers: ['escpos-usb', 'network', 'raw'],
    encoding: 'cp437',
    capabilities: ['usb', 'network', 'raw-bytes', 'escpos', 'images', 'cut-paper'],
    imageSupport: true,
    qrSupport: true,
    barcodeSupport: true,
    cashDrawerSupport: false,
    cutSupport: true,
    isBuiltin: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'builtin-epson-tm-t88',
    name: 'Epson TM-T88 Series',
    model: 'TM-T88',
    paperWidth: '80mm',
    defaultRenderer: 'escpos',
    supportedDrivers: ['escpos-usb', 'network'],
    encoding: 'cp437',
    capabilities: ['usb', 'network', 'escpos', 'images', 'cash-drawer', 'cut-paper'],
    imageSupport: true,
    qrSupport: true,
    barcodeSupport: true,
    cashDrawerSupport: true,
    cutSupport: true,
    isBuiltin: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'builtin-star-tsp100',
    name: 'Star TSP100 Series',
    model: 'TSP100',
    paperWidth: '80mm',
    defaultRenderer: 'escpos',
    supportedDrivers: ['escpos-usb', 'network', 'windows', 'cups'],
    encoding: 'cp437',
    capabilities: ['usb', 'network', 'escpos', 'images', 'cash-drawer', 'cut-paper'],
    imageSupport: true,
    qrSupport: true,
    barcodeSupport: true,
    cashDrawerSupport: true,
    cutSupport: true,
    isBuiltin: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'builtin-generic-pdf-a4',
    name: 'Generic PDF / Office Printer',
    model: null,
    paperWidth: '210mm',
    defaultRenderer: 'pdf',
    supportedDrivers: ['pdf', 'windows', 'cups'],
    encoding: 'utf-8',
    capabilities: ['pdf', 'images'],
    imageSupport: true,
    qrSupport: false,
    barcodeSupport: false,
    cashDrawerSupport: false,
    cutSupport: false,
    isBuiltin: true,
    createdAt: now,
    updatedAt: now,
  },
];
