import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { generateWindowsTaskFiles, type InstallerContext } from '../../src/service/installer/index.js';
import { commandExists, run } from '../common/exec-utils.js';
import type { InstallerLogger } from '../common/installer-logger.js';

const APP_NAME = 'Universal Print Agent';
const REG_UNINSTALL_KEY = 'Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\UniversalPrintAgent';

// NSIS macro references, as plain JS string constants — kept separate from the template literal
// below so no `${...}` in the generated script ever sits immediately after a literal backslash
// (Windows path separators appear throughout this script); that adjacency is what breaks JS
// template-literal parsing regardless of `String.raw`, since `\${` is a parser-level escape.
const M_APP_NAME = '${APP_NAME}';
const M_APP_VERSION = '${APP_VERSION}';
const M_APP_EXE = '${APP_EXE}';
const M_UNINSTALL_KEY = '${UNINSTALL_KEY}';
const M_IF = '${If}';
const M_ENDIF = '${EndIf}';

/**
 * Step 5 — a real NSIS installer script. Reuses the exact same Scheduled-Task generator built in
 * the service-management phase (`generateWindowsTaskFiles`) for service registration — this
 * installer's job is file copying, the registry uninstall entry, and driving those already-built
 * PowerShell scripts, not reinventing Windows service registration.
 *
 * Untestable from this Linux development environment (no Windows, and `makensis` isn't
 * installable here without root — see `buildWindowsInstaller`'s honest staged-source fallback,
 * matching the same pattern already established for RPM/AppImage/mingw). Written to be correct
 * by inspection against standard NSIS idioms, not verified by actually running it.
 */
function generateNsisScript(input: { version: string; runtimeDirName: string }): string {
  const { version, runtimeDirName } = input;
  return `; Generated by installer/windows/nsis-installer.ts — do not edit by hand.
!include "LogicLib.nsh"

!define APP_NAME "${APP_NAME}"
!define APP_VERSION "${version}"
!define APP_EXE "UniversalPrintAgent.exe"
!define UNINSTALL_KEY "${REG_UNINSTALL_KEY}"

Name "${M_APP_NAME}"
OutFile "UniversalPrintAgentSetup.exe"
InstallDir "$PROGRAMFILES64\\Universal Print Agent"
InstallDirRegKey HKLM "${M_UNINSTALL_KEY}" "InstallLocation"
RequestExecutionLevel admin
SetCompressor /SOLID lzma

Page directory
Page instfiles
UninstPage uninstConfirm
UninstPage instfiles

Function .onInit
  ; Upgrade support: if a previous install is registered, stop its service before overwriting files.
  ReadRegStr $0 HKLM "${M_UNINSTALL_KEY}" "InstallLocation"
  ${M_IF} $0 != ""
    DetailPrint "Existing installation detected at $0 — stopping its service before upgrading"
    ExecWait '"$0\\service\\stop-service.ps1"'
  ${M_ENDIF}
FunctionEnd

Section "Install" SEC_INSTALL
  SetOutPath "$INSTDIR"
  File /r "${runtimeDirName}\\*.*"

  ; Runtime folders (Step 2/4) — created empty; the app itself populates config.json/the database.
  CreateDirectory "$INSTDIR\\storage"
  CreateDirectory "$INSTDIR\\logs"
  CreateDirectory "$INSTDIR\\temp"

  ; Service registration + start — reuses the Scheduled-Task scripts generated by
  ; src/service/installer/windows/windows-task.util.ts, staged into service\\ by buildWindowsInstaller.
  DetailPrint "Registering Universal Print Agent as a background service..."
  ExecWait 'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$INSTDIR\\service\\install-service.ps1"'
  ExecWait 'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$INSTDIR\\service\\start-service.ps1"'

  ; Verify API health (Step 5/11) — best-effort; a failure here doesn't abort the install, since
  ; a Scheduled Task triggered ONSTART won't actually be running until next boot unless started now.
  DetailPrint "Verifying REST API health..."
  ExecWait 'powershell.exe -NoProfile -Command "try { Invoke-WebRequest -Uri http://127.0.0.1:3210/api/v1/health -UseBasicParsing -TimeoutSec 10 | Out-Null; exit 0 } catch { exit 1 }"' $1
  ${M_IF} $1 != 0
    DetailPrint "Warning: could not reach http://127.0.0.1:3210/api/v1/health yet — it may still be starting."
  ${M_ENDIF}

  ; Uninstall entry (Step 5)
  WriteRegStr HKLM "${M_UNINSTALL_KEY}" "DisplayName" "${M_APP_NAME}"
  WriteRegStr HKLM "${M_UNINSTALL_KEY}" "DisplayVersion" "${M_APP_VERSION}"
  WriteRegStr HKLM "${M_UNINSTALL_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr HKLM "${M_UNINSTALL_KEY}" "UninstallString" '"$INSTDIR\\Uninstall.exe"'
  WriteRegDWORD HKLM "${M_UNINSTALL_KEY}" "NoModify" 1
  WriteRegDWORD HKLM "${M_UNINSTALL_KEY}" "NoRepair" 1
  WriteUninstaller "$INSTDIR\\Uninstall.exe"
SectionEnd

; Repair (Step 5) — re-running the installer over an existing install is the standard NSIS
; idiom for "repair": every File/CreateDirectory call above is already idempotent, and the
; upgrade-support .onInit stop-before-overwrite logic runs the same way either way.

Section "Uninstall"
  ; Stop and unregister the Scheduled Task before removing files.
  ExecWait 'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$INSTDIR\\service\\stop-service.ps1"'
  ExecWait 'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$INSTDIR\\service\\uninstall-service.ps1"'

  ; Application files only — storage/logs/temp (config, database, printer profiles, logs) are
  ; deliberately left behind, matching installer/scripts/uninstall.ts's default (non---purge)
  ; behavior: reinstalling later picks up right where you left off.
  RMDir /r "$INSTDIR\\node_modules"
  RMDir /r "$INSTDIR\\runtime"
  RMDir /r "$INSTDIR\\service"
  RMDir /r "$INSTDIR\\config-templates"
  Delete "$INSTDIR\\app.cjs"
  Delete "$INSTDIR\\${M_APP_EXE}"
  Delete "$INSTDIR\\LICENSE"
  Delete "$INSTDIR\\README.md"
  Delete "$INSTDIR\\version.json"
  Delete "$INSTDIR\\package.json"
  Delete "$INSTDIR\\package-lock.json"
  Delete "$INSTDIR\\Uninstall.exe"

  DeleteRegKey HKLM "${M_UNINSTALL_KEY}"
SectionEnd
`;
}

/**
 * Stages the runtime package + generated Scheduled-Task scripts into an NSIS source tree, then
 * runs `makensis` if it's available. Otherwise leaves everything staged with the exact command
 * to finish the build on a machine that has NSIS (or on Windows itself) — same honest pattern
 * used for RPM/AppImage.
 */
export async function buildWindowsInstaller(input: {
  runtimeDir: string;
  version: string;
  outputDir: string;
  logger: InstallerLogger;
}): Promise<string | null> {
  const { runtimeDir, version, outputDir, logger } = input;

  const nsisStagingDir = join(outputDir, 'nsis-staging');
  mkdirSync(nsisStagingDir, { recursive: true });

  const serviceDir = join(runtimeDir, 'service');
  mkdirSync(serviceDir, { recursive: true });
  const context: InstallerContext = {
    nodePath: join(runtimeDir, 'runtime', 'bin', 'node.exe'),
    projectRoot: '$INSTDIR',
    entryPoint: '$INSTDIR\\app.cjs',
    logsDir: '$INSTDIR\\logs',
    serviceUser: 'SYSTEM',
  };
  for (const file of generateWindowsTaskFiles(context)) {
    writeFileSync(join(serviceDir, file.relativePath), file.content, 'utf-8');
  }

  const runtimeDirName = 'payload';
  const scriptPath = join(nsisStagingDir, 'installer.nsi');
  writeFileSync(scriptPath, generateNsisScript({ version, runtimeDirName }), 'utf-8');

  const payloadLink = join(nsisStagingDir, runtimeDirName);
  if (!existsSync(payloadLink)) {
    await run('cp', ['-r', runtimeDir, payloadLink]);
  }

  logger.info('Staged NSIS installer script and payload', { scriptPath });

  if (!(await commandExists('makensis'))) {
    logger.warn(
      `makensis not found — NSIS script staged at ${scriptPath}; install NSIS (e.g. 'sudo apt-get install nsis' on Debian/Ubuntu, or from nsis.sourceforge.io on Windows) and run 'makensis ${scriptPath}' to produce UniversalPrintAgentSetup.exe`,
    );
    return null;
  }

  const result = await run('makensis', [scriptPath]);
  if (result.code !== 0) {
    logger.error('makensis failed', { stderr: result.stderr });
    return null;
  }

  const outputPath = join(nsisStagingDir, 'UniversalPrintAgentSetup.exe');
  logger.info('Built Windows installer', { outputPath });
  return outputPath;
}
