import { chmodSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { REPO_ROOT, commandExists, run } from '../common/index.js';
import type { InstallerLogger } from '../common/index.js';
import type { ExecutableArtifact, ReleasePlatform } from './types.js';

/**
 * Step 3 — "package the Node.js application into a standalone executable." Node's own
 * Single-Executable-Application (SEA) feature was evaluated and rejected here: it only supports
 * a CommonJS entry point (this project is ESM, solvable by bundling), but more fundamentally its
 * `require()` inside the embedded entry point is restricted to Node builtins and blob-embedded
 * assets — verified empirically (not from docs alone) that it cannot load *any* real npm
 * dependency from a normal `node_modules` on disk, which makes it a non-starter for an app with
 * native addons (`better-sqlite3`, `usb`) that cannot be embedded in a blob at all.
 *
 * The strategy actually used: bundle first-party `dist/` code into one CommonJS file with
 * esbuild (`--packages=external` — every npm dependency, pure-JS or native, stays a real file in
 * `node_modules`, sidestepping native addons *and* any package's own `import.meta.url`-based
 * asset resolution), then ship a small native launcher next to a private copy of the Node
 * runtime. This is genuinely "doesn't require Node.js to be installed" (we carry our own copy)
 * even though it isn't a single-file blob.
 *
 * This is deliberately behind the `ExecutablePackager` interface so a future tool with real
 * native-addon support (a maintained `pkg` fork, improved SEA) can replace only this file.
 */
export interface ExecutablePackager {
  readonly strategy: string;
  package(input: {
    entryPoint: string;
    outputDir: string;
    platform: ReleasePlatform;
    logger: InstallerLogger;
  }): Promise<{ appBundlePath: string; launcher: ExecutableArtifact }>;
}

function launcherName(platform: ReleasePlatform): string {
  return platform === 'windows' ? 'UniversalPrintAgent.exe' : 'UniversalPrintAgent';
}

function shellLauncherScript(): string {
  return `#!/usr/bin/env bash
# Generated by installer/release/executable-packager.ts — do not edit by hand.
HERE="$(cd "$(dirname "${'${BASH_SOURCE[0]}'}")" && pwd)"
exec "$HERE/runtime/bin/node" "$HERE/app.cjs" "$@"
`;
}

/** A tiny C launcher, cross-compiled for Windows with mingw-w64 when available — see the class doc comment for why this exists instead of a single-file blob. */
function windowsLauncherSource(): string {
  return `// Generated by installer/release/executable-packager.ts — do not edit by hand.
// Launches the bundled Node runtime against app.cjs, both shipped alongside this executable.
#include <windows.h>
#include <stdio.h>

int main(void) {
    char exePath[MAX_PATH];
    GetModuleFileNameA(NULL, exePath, MAX_PATH);
    char *lastSlash = strrchr(exePath, '\\\\');
    if (lastSlash) *lastSlash = '\\0';

    char nodePath[MAX_PATH];
    char appPath[MAX_PATH];
    char cmdLine[MAX_PATH * 2 + 64];
    snprintf(nodePath, sizeof(nodePath), "%s\\\\runtime\\\\bin\\\\node.exe", exePath);
    snprintf(appPath, sizeof(appPath), "%s\\\\app.cjs", exePath);
    snprintf(cmdLine, sizeof(cmdLine), "\\"%s\\" \\"%s\\"", nodePath, appPath);

    STARTUPINFOA si;
    PROCESS_INFORMATION pi;
    ZeroMemory(&si, sizeof(si));
    si.cb = sizeof(si);
    ZeroMemory(&pi, sizeof(pi));

    if (!CreateProcessA(nodePath, cmdLine, NULL, NULL, TRUE, 0, NULL, exePath, &si, &pi)) {
        fprintf(stderr, "Failed to start Universal Print Agent (error %lu)\\n", GetLastError());
        return 1;
    }
    WaitForSingleObject(pi.hProcess, INFINITE);
    DWORD exitCode = 0;
    GetExitCodeProcess(pi.hProcess, &exitCode);
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);
    return (int) exitCode;
}
`;
}

async function bundleToCommonJs(entryPoint: string, outputPath: string, logger: InstallerLogger): Promise<void> {
  const esbuildBin = join(REPO_ROOT, 'node_modules', '.bin', process.platform === 'win32' ? 'esbuild.cmd' : 'esbuild');
  // `src/utils/paths.util.ts` (unmodified — this is a packaging-layer workaround, not a source
  // change) derives PROJECT_ROOT as "two directories above this file", true when it lives at
  // `dist/utils/paths.util.js` but false once bundled flat into one `app.cjs`. The shim below
  // points `import.meta.url` at a *fictional* path two levels under the bundle's real directory
  // purely so that "go up two" arithmetic lands back on the real runtime directory — verified
  // empirically (storage/config.json ended up two directories too high without this).
  const importMetaShim =
    "const importMetaUrlShim = require('url').pathToFileURL(require('path').join(__dirname, '__bundled', 'entry', 'app.cjs')).href;";
  const result = await run(esbuildBin, [
    entryPoint,
    '--bundle',
    '--platform=node',
    '--format=cjs',
    `--outfile=${outputPath}`,
    '--packages=external',
    '--define:import.meta.url=importMetaUrlShim',
    `--banner:js=${importMetaShim}`,
    '--log-level=warning',
  ]);
  if (result.code !== 0) {
    throw new Error(`esbuild bundling failed: ${result.stderr || result.stdout}`);
  }
  logger.info('Bundled first-party code to CommonJS', { outputPath });
}

export function createExecutablePackager(): ExecutablePackager {
  return {
    strategy: 'esbuild-cjs-bundle + native-launcher + private-node-runtime',

    async package({ entryPoint, outputDir, platform, logger }) {
      mkdirSync(outputDir, { recursive: true });
      const appBundlePath = join(outputDir, 'app.cjs');
      await bundleToCommonJs(entryPoint, appBundlePath, logger);

      const launcherPath = join(outputDir, launcherName(platform));

      if (platform === 'windows') {
        const sourcePath = join(outputDir, 'launcher.c');
        writeFileSync(sourcePath, windowsLauncherSource(), 'utf-8');

        const hasMingw = await commandExists('x86_64-w64-mingw32-gcc');
        if (!hasMingw) {
          logger.warn(
            `mingw-w64 not found — Windows launcher staged as source only. Finish with: x86_64-w64-mingw32-gcc -O2 -municode "${sourcePath}" -o "${launcherPath}" (or build launcher.c with MSVC directly on Windows)`,
          );
          return { appBundlePath, launcher: { path: launcherPath, built: false, kind: 'staged-source' } };
        }

        const compile = await run('x86_64-w64-mingw32-gcc', ['-O2', sourcePath, '-o', launcherPath]);
        if (compile.code !== 0) {
          logger.error('mingw-w64 compilation failed', { stderr: compile.stderr });
          return { appBundlePath, launcher: { path: launcherPath, built: false, kind: 'staged-source' } };
        }
        logger.info('Compiled Windows launcher', { launcherPath });
        return { appBundlePath, launcher: { path: launcherPath, built: true, kind: 'native-launcher' } };
      }

      // Linux and macOS both get a shell-script launcher — real, runnable, and (for Linux)
      // actually verified end to end by this pipeline's own verification stage.
      writeFileSync(launcherPath, shellLauncherScript(), 'utf-8');
      chmodSync(launcherPath, 0o755);
      logger.info('Wrote shell launcher', { launcherPath });
      return { appBundlePath, launcher: { path: launcherPath, built: existsSync(launcherPath), kind: 'shell-launcher' } };
    },
  };
}
